postit-template/config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :posts, except: :destroy do 
    resources :comments, only: :create do
      member do
        post :vote
      end
    end

    member do
      post :vote
    end
  end
  resources :users, except: [:destroy] do
    collection do
      get :vote
    end
  end
  resources :categories, only: [:create, :new, :show]
end

postit-template/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
  validates :name, presence: :true, length: {minimum:2}
end

postit-template/app/models/comment.rb
class Comment < ActiveRecord::Base
  include CountVotes
  belongs_to :creator, foreign_key: :user_id, class_name: 'User', inverse_of: :comments
  belongs_to :post, inverse_of: :comments
  has_many :votes, as: :voteable
  validates :body, presence: true



end

postit-template/app/models/post.rb
class Post < ActiveRecord::Base
  include CountVotes
  belongs_to :creator, foreign_key: :user_id, class_name: :User
  has_many :comments, inverse_of: :post
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes ,  as: :voteable
  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true



end

postit-template/app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

postit-template/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments, inverse_of: :creator
  has_secure_password validations: false
  validates :username, presence: true, length: {minimum:5}, uniqueness: true
  validates :password, presence: true, length: {minimum:5}, on: :create
  has_many :votes

  def get_users_last_vote(voteable)
    vote = self.votes.find_by(voteable: voteable)
    vote.vote if vote
  end
end

postit-template/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, foreign_key: :user_id, class_name: :User
  belongs_to :voteable, polymorphic: true


  def self.remove_old_vote voteable, user_id
    previous_vote = Vote.find_by(voteable: voteable, user_id: user_id)
    if previous_vote
      previous_vote.destroy
    end
    previous_vote
  end

end

postit-template/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :log_out, :current_user

  def logged_in?
    session[:user_id] ? true : false
  end

  def log_out
    session[:user_id]  = nil
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    unless logged_in?
      flash[:error] = "You need to be logged in for that!"
      redirect_to root_path
    end
  end
  
end

postit-template/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  protect_from_forgery with: :exception
  
  def new

    @category = Category.new
   
  end

  def create
    @category = Category.new(category_params)
    if @category.save 
      flash[:notice] = "New Category Saved!"
      redirect_to posts_path
    else
    render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

end

postit-template/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Comment has been saved!"
      redirect_to @post 
    else
      render 'posts/show'
    end
  end

  def vote
    @user = current_user
    @comment = Comment.find(params[:id])

    old_vote = Vote.remove_old_vote(@comment, @user.id)
    @vote = Vote.new(vote: params[:direction], user_id: @user.id)
    @vote.voteable = @comment
    if @vote.save
      render json: {new_vote: @vote, old_vote: old_vote}
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

postit-template/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
  before_action :find_post_by_id, only: [:show, :edit, :update]
  before_action :require_user, only: [:new, :create] 

  def index
    @posts = Post.all.sort_by{|post| post.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @user = current_user
    @post.creator = @user

    if @post.save
      flash[:notice] = "Post Has Been Saved"
      redirect_to posts_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
  
    if @post.update(post_params)
      flash[:notice] = "Post Updated!"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def vote
    @user = current_user
    @post = Post.find(params[:id])
    old_vote = Vote.remove_old_vote(@post, @user.id)
    @vote = Vote.new(vote: params[:direction], user_id: @user.id)
    @vote.voteable = @post
    if @vote.save
      render json: {new_vote: @vote, old_vote: old_vote}
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :description, :user_id, :category_ids => [])
  end


  def find_post_by_id
    @post = Post.find(params[:id])
  end
end

postit-template/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session
  end  

  def create

    @user = User.find_by username: params[:username]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Successfully Logged In!"
      redirect_to root_path
    else
      flash[:error] = "Something Wrong with your Log In!"
      render 'sessions/new'
    end
  end

  def destroy
    log_out
    flash[:notice] = "You have been logged out!"
    redirect_to root_path

  end
  
end

postit-template/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:create, :vote, :new]
  before_action :get_user, only: [:show, :update, :edit]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User has been created successfully"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end

  end

  def show
  end

  def update
    @user.update(user_params)
    if @user.save
      flash[:notice] = "User has been updated successfully"
      redirect_to edit_user_path
    else
      render 'edit'
    end

  end



  def edit
  end

  def vote
    render json:{vote:current_user.votes}
    
  end

  private
  def user_params
    params.require(:user).permit(:username,:password)

  end

  def get_user
    if User.exists?(params[:id])
      @user = User.find params[:id]
    else
      flash[:error] = "You cannot go there."
      redirect_to root_path
    end
  end
  def require_same_user
    if current_user != @user
      flash[:error] = "You can't do that!"
      redirect_to root_path
    end
  end
end

postit-template/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  

end

postit-template/app/helpers/application_helper.rb
module ApplicationHelper

  def date_fix(date)
    date.strftime("%m/%d/%Y %l: %M%P %Z")
  end
end

postit-template/app/views/comments/_comment.html.erb
 <div class="row">
 <% if logged_in? %>
  <%= react_component :VoteBox, votes: comment.votes, total_votes: comment.total_votes, url: vote_post_comment_path(comment.post, comment), last_vote: current_user.get_users_last_vote(comment) %>
  <% end %>

<div class="span8 well">

    <em>" <%= comment.body %> "</em> <% if link_to %>
      <span> from <%= link_to comment.post.title, post_path(comment.post)  %></span>
    <% end %>
    <p><span class='quiet'>posted by</span> <%=comment.creator.username%></p> 
    
    <small> @ <%=date_fix comment.created_at%> </small>
</div>
</div>

postit-template/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

postit-template/app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>

</ul>
<div class="btn-group nav_item">
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class='caret'></span>
    <% end %>
    <ul class="dropdown-menu">
      <% Category.all.each do |category| %>
        <li><%= link_to category.name, category %></li>
      <% end %>
      <%if logged_in? %>
        <li class='divider'></li>
        <li> <%= link_to(new_category_path) do %>
          <i class="icon-plus"></i> New Category
          <% end %>
        </li>
      <% end %>
    </ul>

</div>


<% if logged_in? %>
<div class='nav_item'>
     <%= link_to 'Create Post', new_post_path, class: 'btn btn-small' %>
</div>

<div class="btn-group nav_item">
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
  <%= current_user.username%>
    <span class='caret'></span>
    <% end %>
    <ul class="dropdown-menu">

     <li><%= link_to 'View Profile', user_path(current_user) %></li>
     <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
     <li><%= link_to 'Log out', logout_path  %></li>
  
    </ul>

</div>

<% else %>
<div class='nav_item'>
     <%= link_to 'Register', register_path, class: 'btn btn-small' %>
</div>

<div class='nav_item'>
     <%= link_to 'Log In', login_path, class: 'btn btn-small' %>
</div>  

<% end %>

postit-template/app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

postit-template/app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class = "well">
  <%= form_for @post do |f| %>
    <div class='control-group'>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>
    
    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %> <br>
    </div>
    <div class='control-group'>
     <%= f.label "Categories" %>
      </div>

    <%=   f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
     <%= b.label class: "checkbox inline" %> <%=b.check_box class: "checkbox" %>
    
    <% end %>
    <br>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
 
</div>

postit-template/app/views/posts/_post.html.erb
<div class="row">
  <% if logged_in? %>
  <%= react_component :VoteBox, votes: post.votes, url: vote_post_path(post), total_votes: post.total_votes,last_vote: current_user.get_users_last_vote(post) %>
  <% end %>
  
  <div class='span8 well'>
   <% post.categories.each do |category| %>
      <%= react_component "Category",
      {name: category.name, id: category.id} %>
   <% end %>
    <h4><%= link_to post.title, post %></h4>

    <p><%= post.description %></p>

    <% if post.creator %>
    <p><span class='quiet'>posted by</span> <%=post.creator.username%></p>
    <% end %>
    
    <%= link_to "#{post.comments.size} comments", post_path(post) %> 
    <% if post.created_at %>
    <small> @ <%= date_fix post.created_at%> </small>
    <%end %>
  </div>
</div>

postit-template/app/views/posts/edit.html.erb
<h4>Edit Post </h4>
<%= render 'form' %>

postit-template/app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Post' %>

<%= render @posts %>

postit-template/app/views/posts/new.html.erb
<% all_posts = link_to('All Posts',posts_path) %>
<%= render 'shared/content_title', title: "#{all_posts} &raquo; Create New Post".html_safe %>

<%= render 'form' %>

postit-template/app/views/posts/show.html.erb
<%= render 'shared/errors', obj: @comment %>


<% all_posts = link_to('All Posts',posts_path) %>
<p class='pull-right'>[<%= link_to 'edit this post', edit_post_path(@post)%>]</p>
<p>
<%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@post.title}".html_safe%>

<p><%= @post.description %>
<hr/></p>
<p><%=link_to 'back', posts_path %></p>
<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.label :body, 'Leave a comment' %>
    <%= f.text_area :body, rows: 3, class: 'span4' %>
    <br>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= render @post.comments, link_to: false %>

postit-template/app/views/shared/_content_title.html.erb
<p class = 'lead'>
<%= title %>
<hr/>
</p>  

postit-template/app/views/shared/_created_by.html.erb
    <% if obj.creator %>
    <p><span class='quiet'>posted by</span> <%=obj.creator.username%></p>
    <% end %>
    
    <%= link_to "#{obj.comments.size} comments", obj_path(obj) %> 
    <% if obj.created_at %>
    <small> @ <%=obj.created_at%> </small>
    <%end %>

postit-template/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class='alert alert-error span8'>
    
      <h4> The Following Errors Occurred: </h4>
        <% obj.errors.full_messages.each do |error| %>
          <li> <%=error %> </li>
        <% end %>
  </div>
</div>
<% end %>

postit-template/app/views/shared/_user_form.html.erb
<div class = "well">
  <%= form_for @user do |f| %>
    <div class='control-group'>
    <%= f.label :username %>
    <%= f.text_field :username %>
    </div>
    
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <br>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
 
</div>